"""empty message

Revision ID: 20a6a64ed2f4
Revises: a87827e0be04
Create Date: 2019-06-07 19:03:03.798756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20a6a64ed2f4'
down_revision = 'a87827e0be04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_token',
    sa.Column('notification_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('notification_token')
    )
    op.drop_constraint('map_name_key', 'map', type_='unique')
    op.alter_column('post', 'point_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('post', 'point_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'point_y',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('post', 'point_x',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint('map_name_key', 'map', ['name'])
    op.drop_table('notification_token')
    # ### end Alembic commands ###
