"""empty message

Revision ID: a87827e0be04
Revises: 
Create Date: 2019-05-26 23:44:33.729283

"""
from alembic import op
from sqlalchemy import orm
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87827e0be04'
down_revision = None
branch_labels = None
depends_on = None


from sqlalchemy.sql import table, column
from sqlalchemy import String
from alembic import op





def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('user_id', sa.String(), nullable=True))

    user_id = table('map', column('user_id')) 

    op.execute(user_id.update().values(user_id='b9hgSznuuXOT1FaGh1LpsqmR5S92'))       

    op.alter_column('map', 'user_id', nullable=False)

    op.create_foreign_key(None, 'map', 'user', ['user_id'], ['id']) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.drop_column('map', 'user_id')
    # ### end Alembic commands ###
